# Generated by Django 6.0.5 on 2026-05-13 04:04

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'assistant',
            },
        ),
        migrations.CreateModel(
            name='Attorney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'attorney',
            },
        ),
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'body_part',
            },
        ),
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'case_status',
            },
        ),
        migrations.CreateModel(
            name='ClaimAdjuster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'claim_adjuster',
            },
        ),
        migrations.CreateModel(
            name='ClaimAdministrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'claim_administrator',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('ssn', models.CharField(blank=True, max_length=30, null=True)),
                ('birth', models.DateField(null=True)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='DefenseAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'defense_assistant',
            },
        ),
        migrations.CreateModel(
            name='DefenseAttorney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'defense_attorney',
            },
        ),
        migrations.CreateModel(
            name='DefenseLawFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'defense_law_firm',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'employer',
            },
        ),
        migrations.CreateModel(
            name='InjuryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'injury_type',
            },
        ),
        migrations.CreateModel(
            name='InsuranceCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'insurance_carrier',
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('attorney', 'Attorney'), ('assistant', 'Assistant')], default='admin', max_length=20)),
            ],
            options={
                'db_table': 'system_user',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClaimAdjusterContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('phone', '📞'), ('email', '🖂'), ('fax', '🖷')], default='phone', max_length=30)),
                ('value', models.CharField(max_length=50)),
                ('notes', models.CharField(blank=True, max_length=50, null=True)),
                ('claim_adj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='case_manager.claimadjuster')),
            ],
            options={
                'db_table': 'claim_adj_contact',
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('phone', '📞'), ('email', '🖂'), ('fax', '🖷')], default='phone', max_length=30)),
                ('value', models.CharField(max_length=50)),
                ('notes', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='case_manager.client')),
            ],
            options={
                'db_table': 'client_contact',
            },
        ),
        migrations.CreateModel(
            name='DefenseAssistantContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('phone', '📞'), ('email', '🖂'), ('fax', '🖷')], default='phone', max_length=30)),
                ('value', models.CharField(max_length=50)),
                ('notes', models.CharField(blank=True, max_length=50, null=True)),
                ('def_assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='case_manager.defenseassistant')),
            ],
            options={
                'db_table': 'def_assistant_contact',
            },
        ),
        migrations.CreateModel(
            name='DefenseAttorneyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('phone', '📞'), ('email', '🖂'), ('fax', '🖷')], default='phone', max_length=30)),
                ('value', models.CharField(max_length=50)),
                ('notes', models.CharField(blank=True, max_length=50, null=True)),
                ('def_attorney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='case_manager.defenseattorney')),
            ],
            options={
                'db_table': 'def_attorney_contact',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('adj_date', models.DateField(blank=True, null=True)),
                ('adj_num', models.CharField(blank=True, max_length=40, null=True)),
                ('claim_num', models.CharField(blank=True, max_length=40, null=True)),
                ('claim_status', models.CharField(blank=True, choices=[('denied', 'Denied'), ('delayed', 'Delayed'), ('accepted', 'Accepted')], max_length=10, null=True)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('date_assigned', models.DateField(blank=True, help_text='Fecha en que el caso fue asignado a la firma o al asistente', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='case_manager.assistant')),
                ('attorney', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='case_manager.attorney')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='case_manager.casestatus')),
                ('claim_adjuster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='case_manager.claimadjuster')),
                ('claim_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='case_manager.claimadministrator')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='case_manager.client')),
                ('def_assistant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='case_manager.defenseassistant')),
                ('def_attorney', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='case_manager.defenseattorney')),
                ('def_lawfirm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='case_manager.defenselawfirm')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='case_manager.employer')),
                ('insurance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='case_manager.insurancecarrier')),
            ],
            options={
                'db_table': 'case',
            },
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='case_manager.case')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_manager.bodypart')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_manager.injurytype')),
            ],
            options={
                'db_table': 'injury',
            },
        ),
        migrations.AddField(
            model_name='attorney',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attorney', to='case_manager.systemuser'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant', to='case_manager.systemuser'),
        ),
    ]
