# Generated by Django 6.0.4 on 2026-04-27 19:31

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'assistant',
            },
        ),
        migrations.CreateModel(
            name='Attorney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'attorney',
            },
        ),
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'body_part',
            },
        ),
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'case_status',
            },
        ),
        migrations.CreateModel(
            name='ClaimAdjuster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'claim_adjuster',
            },
        ),
        migrations.CreateModel(
            name='ClaimAdministrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'claim_administrator',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('ssn', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='DefenseAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'defense_assistant',
            },
        ),
        migrations.CreateModel(
            name='DefenseAttorney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'defense_attorney',
            },
        ),
        migrations.CreateModel(
            name='DefenseLawFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'defense_law_firm',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employer',
            },
        ),
        migrations.CreateModel(
            name='InjuryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'injury_type',
            },
        ),
        migrations.CreateModel(
            name='InsuranceCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'insurance_carrier',
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('visible', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('attorney', 'Attorney'), ('assistant', 'Assistant')], max_length=20)),
            ],
            options={
                'db_table': 'system_user',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('contact_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('fax', 'Fax')], max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('adj_num', models.CharField(max_length=50)),
                ('adj_date', models.DateField(blank=True, null=True)),
                ('claim_num', models.CharField(max_length=100)),
                ('claim_status', models.CharField(max_length=100)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case_manager.assistant')),
                ('attorney', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case_manager.attorney')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case_manager.casestatus')),
                ('claim_adjuster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case_manager.claimadjuster')),
                ('claim_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case_manager.claimadministrator')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case_manager.client')),
                ('def_assistant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case_manager.defenseassistant')),
                ('def_attorney', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case_manager.defenseattorney')),
                ('def_lawfirm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case_manager.defenselawfirm')),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case_manager.employer')),
                ('ins_carrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case_manager.insurancecarrier')),
            ],
            options={
                'db_table': 'case',
            },
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('body_part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case_manager.bodypart')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='case_manager.case')),
                ('injury_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case_manager.injurytype')),
            ],
            options={
                'db_table': 'injury',
            },
        ),
        migrations.AddField(
            model_name='attorney',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_manager.systemuser'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_manager.systemuser'),
        ),
    ]
