# Generated by Django 6.0.4 on 2026-04-27 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='injury',
            old_name='injury_type',
            new_name='type',
        ),
    ]
