# Generated by Django 6.0.5 on 2026-05-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodypart',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='claimadjuster',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='claimadministrator',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='defenseassistant',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='defenseattorney',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='defenselawfirm',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='injurytype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='insurancecarrier',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
