# Generated by Django 6.0.5 on 2026-05-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0002_alter_bodypart_name_alter_claimadjuster_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimadministrator',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='defenselawfirm',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='insurancecarrier',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
