# Generated by Django 6.0.4 on 2026-04-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0002_rename_injury_type_injury_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimadministrator',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='defenselawfirm',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecarrier',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
