# Generated by Django 6.0.4 on 2026-05-05 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0003_alter_claimadministrator_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='case_manager.systemuser'),
        ),
        migrations.AlterField(
            model_name='attorney',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='case_manager.systemuser'),
        ),
    ]
