# Generated by Django 6.0.4 on 2026-05-08 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0004_alter_assistant_user_alter_attorney_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant', to='case_manager.systemuser'),
        ),
        migrations.AlterField(
            model_name='attorney',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attorney', to='case_manager.systemuser'),
        ),
    ]
