# Generated by Django 6.0.5 on 2026-05-13 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0004_historicalcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injury',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='case_manager.injurytype'),
        ),
    ]
