# Generated by Django 6.0.5 on 2026-05-15 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0005_alter_injury_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='claim_adjuster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='case_manager.claimadjuster', verbose_name='Claim Adjuster'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='claim_adjuster',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='case_manager.claimadjuster', verbose_name='Claim Adjuster'),
        ),
    ]
