# Generated by Django 6.0.5 on 2026-05-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0006_alter_case_claim_adjuster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
