# Generated by Django 6.0.5 on 2026-05-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0007_case_comments_historicalcase_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestatus',
            name='terminal',
            field=models.BooleanField(default=False),
        ),
    ]
