# Generated by Django 6.0.5 on 2026-06-18 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0008_casestatus_terminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='claim_adjuster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='case_manager.claimadjuster'),
        ),
        migrations.AlterField(
            model_name='case',
            name='date_assigned',
            field=models.DateField(blank=True, help_text='Fecha en que el caso fue asignado.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='claim_adjuster',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='case_manager.claimadjuster'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='date_assigned',
            field=models.DateField(blank=True, help_text='Fecha en que el caso fue asignado.', null=True),
        ),
    ]
